### PR TITLE
new example from video stream and video4linux

### PR DESCRIPTION
**Pull request by dehann**

### CODE REVIEW

**Comment by dehann** [comment]
I think there is a lot of new memory being created in the current conversion code.  I'm guessing there is room for major speedups with Video4Linux if we use `view`, `colorview`, and `normedview` more extensively. We want `@time` or `@btime` to read very low levels of new memory consumption... I will commit what I have to v4l.

**Comment by Affie** [comment]
Thanks, I think you are correct that there is a lot of room for speedups and any help is much appreciated.
Just take note we found a memory leak in imshow https://github.com/JuliaImages/ImageView.jl/issues/138.

**Comment by dehann** [comment]
Will certainly help with the speedups.  I think it is okay to merge the first example.  It would probably be better to move the second LCM message example elsewhere... Maybe directly to `Caesar.jl` since the LCM types are stored in `CaesarLCMTypes.jl`.

**Comment by dehann** [comment]
xref dehann/Caesar.jl#102

**Comment by Affie** [comment]
@dehann, I changed the imshow to avoid the memory leak. It should perform way better now.

**Comment by dehann** [comment]
Hi, Thanks!

**Comment by dehann** [comment]
can merge if ready.

**Comment by dehann** [comment]
cc @GearsAD, for the less leaky memory `imshow` canvas update.

**Pull request merged**
