### PR TITLE
Add April Cal Grid Cailbration

### PR DESCRIPTION
**Pull request by dehann**
Must first finish #63 since current API conventions are all mixed up.

### CODE REVIEW

**Comment by dehann** [comment]
HI @Affie , thanks FYI similar renaming for `f_width` and `c_height` to overcome much confusion.

**Comment by Affie** [comment]
Hi @dehann, my preference is still to follow the apriltag library and perhaps just document it clearly here also. If you use a library such as openCV or even ROS to calibrate your camera you get fx,fy,cx,cy. 
For me, width and height make it less clear if you work with the tag pose, x-y-z follows the right-hand rule and is standard.

Alternatively, we can have a diagram in the docs that show that fx is f_width and so on.

**Comment by dehann** [comment]
i think the x is the confusing part because it is used by both conventions.  right hand rule should always be followed.  I'm a bit frustrated with fx, cx because it clashes with Array convention and right hand rule.  I want her core verbose so the user knows exactly what is going on.  there is only one width and one height, and that overcomes the (x,y) vs (y,x) that gets smeared under (X,Y)

**Comment by dehann** [comment]
we can document that fx, cx in the library is f_width, and c_width.  User is responsible for choosing whether they want to use (y,x), (u,v), (i,j).  But it must always be right hand rule.  Never add anything that is left hand rule.

i tried reading the current documentation but was not clear.  So how about keeping the low level '_verb...' wrappers as cx and fy, and high level functions as c_width f_height.  

I've been battling with the convention for days now and want a permanent fix for the problem

**Comment by dehann** [comment]
we should definitely do a diagram

**Comment by Affie** [comment]
We should maybe repeat some of the apriltag c library docs. I just documented the julia interface part. There is a bunch of people that also get confused over there.
Also the tag size.

**Comment by dehann** [comment]
I definitely want to find a solution that works for both of us, because then it should be good for wider audience.  I'll update here and call again

**Pull request merged**
